export enum TipoCampo {
    CHECKBOX = '{"value": "CHECKBOX", "label": "CHECKBOX"}',
    CNPJ = '{"value": "CNPJ", "label": "CNPJ"}',
    COLOR = '{"value": "COLOR", "label": "COR"}',
    CPF = '{"value": "CPF", "label": "CPF"}',
    CPF_CNPJ = '{"value": "CPF_CNPJ", "label": "CPF E CNPJ"}',
    DATE = '{"value": "DATE", "label": "DATA"}',
    EMAIL = '{"value": "EMAIL", "label": "E-MAIL"}',
    NUMBER = '{"value": "NUMBER", "label": "NÚMERO"}',
    PASSWORD = '{"value": "PASSWORD", "label": "SENHA"}',
    RADIO = '{"value": "RADIO", "label": "RADIO"}',
    SELECT = '{"value": "SELECT", "label": "SELECT"}',
    SELECT_SN =  '{"value": "SELECT_SN", "label": "SELECT (SIM/NÃO)"}',
    SELECT_VF = '{"value": "SELECT_VF", "label": "SELECT (VERDADEIRO/FALSO)"}',
    TELEFONE_DDD = '{"value": "TELEFONE_DDD", "label": "TELEFONE COM DDD"}',
    TEXT = '{"value": "TEXT", "label": "TEXT"}',
    TEXTAREA = '{"value": "TEXTAREA", "label": "TEXTAREA"}',
    TIME = '{"value": "TIME", "label": "HORA"}',
    URL = '{"value": "URL", "label": "URL"}',
    CEP = '{"value": "CEP", "label": "CEP"}',
    HIDDEN = '{"value": "HIDDEN", "label": "HIDDEN"}',
    CEP_ONLINE = '{"value": "CEP_ONLINE", "label": "CEP ONLINE"}',
    MONETARIO = '{"value": "MONETARIO", "label": "MONETÁRIO"}',
    DECIMAL = '{"value": "DECIMAL", "label": "DECIMAL"}',
    CONTA_CAIXA = '{"value": "CONTA_CAIXA", "label": "CONTA CAIXA"}'
}