
			
'use strict';

angular.module('webApp').config(['$translateProvider', function($translateProvider) {
	$translateProvider.translations('en', {
		'label.sucesso' : 'Sucess',
		'label.falha.listar.controller' : 'Failed to list ',
		'label.falha.incluir.controller' : 'Failed to include ',
		'label.falha.verificar.inscricao' : 'Failed to perform verification of incoming email enrollment',
		'label.aplicacao.restrita.informe.email' : 'Restricted application, please report the email',
		'label.aplicacao.restrita.informe.codigo.acesso' : 'Restricted application, enter the access code',
		'label.codigo.acesso.autorizado.contate.responsavel.projeto' : 'Unauthorized access code, contact the project manager',
		'label.atencao' : 'Attention!',
		'label.funcionou' : 'It worked!',
		'label.invalido' : 'Invalid.',
		'label.cliente' : 'Client',
		'label.vazio' : 'Empty!',
		'label.upload.realizado.com.sucesso' : 'Successfully uploaded',
		'label.selecione.algum.arquivo.para.upload' : 'Select some file to upload',
		'label.api.arquivos.nao.suportadas.neste.navegador' : 'File APIs are not fully supported in this browser.',
		'label.assinatura.efetuada.com.sucesso' : 'Signed successfully',
		'label.falha.ao.efetuar.assinatura' : 'Failed to sign',
		'label.cancelamento.efetuado.com.sucesso' : 'Successful cancellation',
		'label.assinatura.recebimento.email.realizada.com.sucesso' : 'Signature to successfully receive email',
		'label.falha.efetuar.inscricao.recebimento.email' : 'Failed to sign up to receive email',
		'label.cancelamento.recebimento.email.realizado.sucesso' : 'Cancellation of successful email receiving',
		'label.falha.efetuar.cancelamento.recebimento.email' : 'Failed to cancel receiving email',
		'label.modo.desenvolvimento' : 'Development Mode',
		'label.informe.codigo.desenvolvimento' : 'Enter the development code',
		'label.exclusao.confirmada.pelo.usuario' : 'Deletion confirmed by user',
		'label.exclusao.cancelada.pelo.usuario' : 'Deletion canceled by user',
		'label.confirma.exclusao.deste.item' : 'Do you confirm the deletion of this item?',
		'label.navegacao.suspensa.click.ok' : 'Navigation suspended during editing. Click OK to proceed',
		'label.sua.opiniao.foi.enviada.com.sucesso' : 'Your review was submitted successfully! Thank you for participating',
		'label.faltou.avaliar.quesito' : 'You missed the item ',
		'label.nome.da.mensagem' : 'Message Name',
		'label.titulo.da.mensagem' : 'Message Title',
		'label.conteudo.da.mensagem' : 'Message Content',
		'label.confirma.remover.esta.acao' : 'Do you confirm to remove this action?',
		'label.informe.o.nome2' : 'Enter the name',
		'label.informe.o.titulo' : 'Report Title',
		'label.informe.a.mensagem' : 'Report the Message',
		'label.titulo.do.email' : 'Email Title',
		'label.titulo.a.mensagem' : 'Message Title',
		'label.conteudo.a.mensagem' : 'Message Content',
		'label.sua.mensagem.foi.enviada.com.sucesso' : 'Your message has been sent successfully!',
		'label.informe.o.titulo.do.email' : 'Enter your email title',
		'label.informe.a.mensagem.do.email' : 'Enter the email message',
		'label.adicione.um.destinatario' : 'Add a recipient',
		'label.fechar' : 'Close',
		'label.abrir' : 'Open',
		'label.enviar' : 'Submit',
		'label.deixe.aqui.suas.criticas.sugestoes' : 'Leave your comments or suggestions here (optional)',
		'label.ajude.melhorar.esta.aplicacao.enviando.opiniao' : 'Help us improve this app by sending us your opinion',
		'label.avaliacao.usuario' : 'User Rating',
		'label.gostaria.receber.notificacoes.central.caixa' : 'Would you like to receive notifications from Central Caixa?',
		'label.sim.eu.quero' : 'Yes I want!',
		'label.nao.obrigado' : 'No thank you.',
		'label.nao.receber.emails' : 'DO NOT RECEIVE EMAILS',
		'label.clique.para.cancelar.recebimento.emails' : 'Click to cancel receiving emails',
		'label.receber.email' : 'RECEIVE EMAILS',
		'label.clique.para.assinar.canal.recebimento.emails' : 'Click to sign the channel to receive emails',
		'label.ir.para.conteudo' : 'Go to the content (ALT + 1)',
		'label.ir.para.menu' : 'Go to menu (ALT + 2)',
		'label.clique.aqui.para.finalizarAtendimento': 'Clique Aqui Para Finalizar o Atendimento',
		'label.finalizarAtendimento': 'Finalizar Atendimento',
		'label.clique.aqui.para.cancelar.atendimento': 'Click here to cancel the service',
		'label.cancelar.atendimento': 'Cancel Service',		
		'label.erro.alteracao.limite': 'Alteração do campo além do limite',
		'label.informe.o.cep.residencial': 'Informe o CEP Residencial',
		'label.informe.o.tipo.logradouro.residencial': 'Informe o Tipo Logradouro Residencial',
		'label.informe.o.logradouro.residencial': 'Informe o Logradouro Residencial',
		'label.informe.o.numero.residencial': 'Informe o Número Residencial',
		'label.informe.o.complemento.residencial': 'Informe o Complemento Residencial',
		'label.informe.o.bairro.residencial': 'Informe o Bairro Residencial',
		'label.informe.o.uf.residencial': 'Informe o UF Residencial',
		'label.informe.o.cidade.residencial': 'Informe a Cidade da Residencia',
		'label.informe.o.nome.social': 'Informe o Nome Social',
		'label.nome.social': 'Nome Social',
		'label.informe.o.cep.comercial': 'Informe o CEP Comercial',
		'label.informe.o.tipo.logradouro.comercial': 'Informe o Tipo Logradouro Comercial',
		'label.informe.o.logradouro.comercial': 'Informe o Logradouro Comercial',
		'label.informe.o.numero.comercial': 'Informe o Número Comercial',
		'label.informe.o.complemento.comercial': 'Informe o Complemento Comercial',
		'label.informe.o.bairro.comercial': 'Informe o Bairro Comercial',
		'label.informe.o.uf.comercial': 'Informe o UF Comercial',
		'label.informe.o.cidade.comercial': 'Informe a Cidade do Comércio',
		'label.endereco.residencial': 'Endereço Residencial',
		'label.dados.pessoais': 'Dados Pessoais',
		'label.endereco.comercial': 'Endereço Comercial',
		'label.numero': 'Número',
		'label.cep.mask': '99999-999',
		'label.informe.o.patrimonio' : 'Informe o Patrimônio',
		'label.informe.o.valor.expresso' : 'Valor total expresso (R$)',
		'label.selecione.celular' : 'Selecione o celular',
		
		"label." : "english example",
		"label.." : "english example",
		"label.1.000.399.368-05.maria.zilda.pagotti" : "english example",
		"label.1.999.999.999-99.fulano.de.tal" : "english example",
		"label.2.132.120.827-80.fulano.de.tal" : "english example",
		"label.abertura.conta.dossi.digital" : "english example",
		"label.abertura.de.conta" : "english example",
		"label.abertura.de.conta.dossi.digital" : "english example",
		"label.abertura.de.conta.resultado" : "english example",
		"label.abrir.conta/contratar.servios" : "english example",
		"label.adeso..servios" : "english example",
		"label.agncia:.0002.-.planalto,.df" : "english example",
		"label.agncia:.0002.-.planalto,df" : "english example",
		"label.aprovao.da.abertura.de.conta" : "english example",
		"label.aprovao.do.cadastro" : "english example",
		"label.aprovar" : "english example",
		"label.assinatura.do.cliente" : "english example",
		"label.assinatura.do.gerente" : "english example",
		"label.assinatura.do.gerente.final" : "english example",
		"label.assinatura.eletrnica" : "english example",
		"label.atualizar" : "english example",
		"label.atualizar.cnh" : "english example",
		"label.atualizar.rg" : "english example",
		"label.autoriza.o.envio.de.informaes.do.fgts?" : "english example",
		"label.autorizao.documental" : "english example",
		"label.autorizao.nº.0123456783" : "english example",
		"label.avaliaes.vlidas.-.siric" : "english example",
		"label.avaliao.de.risco" : "english example",
		"label.avaliao.de.risco.-.cliente.comercial" : "english example",
		"label.avaliao.de.risco.-.operao.comercial" : "english example",
		"label.avaliao.de.risco.cliente.comercial" : "english example",
		"label.avaliao.de.risco.operao" : "english example",
		"label.avaliar.op..crdito" : "english example",
		"label.bairro" : "english example",
		"label.bandeira" : "english example",
		"label.boto" : "english example",
		"label.boto.imagem" : "english example",
		"label.cadastramento.da.senha.do.cliente" : "english example",
		"label.cadastramento.de.senha.cliente" : "english example",
		"label.cadastrar" : "english example",
		"label.cadastro" : "english example",
		"label.cadastro.de.assinatura.eletrnica.no.pde.ser.efetuado" : "english example",
		"label.caixa.de.texto" : "english example",
		"label.caixa.seguros" : "english example",
		"label.cancelar" : "english example",
		"label.cancelar.emails" : "english example",
		"label.cancelar.notificaes" : "english example",
		"label.cargo.do.funcionrio" : "english example",
		"label.carregando..." : "english example",
		"label.carto.assinatura" : "english example",
		"label.cedesrj.-.caixa.econmica.federal" : "english example",
		"label.celular:.(011).99999-9999.-.data.de.referncia.dd/mm/aaaa.[excluir]" : "english example",
		"label.cep" : "english example",
		"label.cesta.de.servios" : "english example",
		"label.cheque.especial.implantado.com.sucesso" : "english example",
		"label.cidade" : "english example",
		"label.cidade/uf,.dd.de.mm.de.aaaa" : "english example",
		"label.cliente.comercial" : "english example",
		"label.clique.aqui.para" : "english example",
		"label.clique.aqui.para.abrir.conta/contratar.servios" : "english example",
		"label.clique.aqui.para.aprovar" : "english example",
		"label.clique.aqui.para.atualizar" : "english example",
		"label.clique.aqui.para.avaliar.op..crdito" : "english example",
		"label.clique.aqui.para.cancelar" : "english example",
		"label.clique.aqui.para.consultar" : "english example",
		"label.clique.aqui.para.continuar" : "english example",
		"label.clique.aqui.para.digitalizar" : "english example",
		"label.clique.aqui.para.exibir.documento" : "english example",
		"label.clique.aqui.para.imprimir.documentos.contratuais" : "english example",
		"label.clique.aqui.para.incluir" : "english example",
		"label.clique.aqui.para.ir.para.cliente.comercial" : "english example",
		"label.clique.aqui.para.localizar.cliente" : "english example",
		"label.clique.aqui.para.não.receber.emails" : "english example",
		"label.clique.aqui.para.não.receber.notificaes" : "english example",
		"label.clique.aqui.para.ocultar.documento" : "english example",
		"label.clique.aqui.para.receber.emails" : "english example",
		"label.clique.aqui.para.receber.notificaes" : "english example",
		"label.clique.aqui.para.visualizar.o.comprovante.de.identificao" : "english example",
		"label.clique.aqui.para.visualizar.o.comprovante.de.rendimento" : "english example",
		"label.clique.aqui.para.visualizar.o.comprovante.de.residncia" : "english example",
		"label.clique.aqui.para.voltar" : "english example",
		"label.clique.para.cadastrar" : "english example",
		"label.clique.para.cadastrar.nova.senha" : "english example",
		"label.clique.para.cadastrar.um.novo.usurio" : "english example",
		"label.clique.para.deslogar" : "english example",
		"label.clique.para.enviar.nova.senha" : "english example",
		"label.clique.para.instalar.a.verso.mobile" : "english example",
		"label.clique.para.logar" : "english example",
		"label.clique.para.retornar" : "english example",
		"label.clique.para.trocar.a.senha" : "english example",
		"label.cnh" : "english example",
		"label.cnpj" : "english example",
		"label.cocli.da.fonte.pagadora" : "english example",
		"label.complemento" : "english example",
		"label.compras.com.carto.de.dbito.a.partir.de" : "english example",
		"label.comprovante.de.renda" : "english example",
		"label.comprovante.de.residncia" : "english example",
		"label.concorda.em.participar.de.campanhas.de.incentivo.da.caixa.com.premiao?" : "english example",
		"label.confirmar.a.senha" : "english example",
		"label.consulta.avaliaes.vlidas" : "english example",
		"label.consulta.avaliaes.vlidas.aprovadas" : "english example",
		"label.consultar" : "english example",
		"label.conta.aberta.com.sucesso" : "english example",
		"label.contato" : "english example",
		"label.contatos:.telefone./.comum.-.residencial.atual.-.(61).3206-7676" : "english example",
		"label.continuar" : "english example",
		"label.contrata.seguro.do.carto?" : "english example",
		"label.contratao.de.produtos" : "english example",
		"label.contratao.de.servios.de.mensagem.via.celular.no.pde.ser.efetuada" : "english example",
		"label.correio.eletrnico.(email):.teste@teste.com.br" : "english example",
		"label.cpf" : "english example",
		"label.datanascimento" : "Bird date",
		"label.cpf:.000.399.368-05" : "english example",
		"label.cpf.do.cnjuge" : "english example",
		"label.cpf.do.cliente:.132.120.827-80" : "english example",
		"label.cpf.do.responsvel:.999.999.999-99" : "english example",
		"label.cpf.informado.est.com.situao.regular.perante.a.receita.federal." : "english example",
		"label.curador(es)" : "english example",
		"label.dados.da.conta" : "english example",
		"label.dados.declarados" : "english example",
		"label.dados.do.titular" : "english example",
		"label.dados.do(s).titular(es)" : "english example",
		"label.data.de.admisso/incio" : "english example",
		"label.data.de.cadastramento" : "english example",
		"label.data.de.dbito.(juros)" : "english example",
		"label.data.de.nascimento:.21/03/1956" : "english example",
		"label.data.de.nascimento:.27/04/1958" : "english example",
		"label.data.de.nascimento:.27/04/1988" : "english example",
		"label.data.de.nascimento.do.cnjuge" : "english example",
		"label.ddd.e.nmero" : "english example",
		"label.declaracoes" : "Declarações",
		"label.declarao.de.dados" : "english example",
		"label.declarao.de.propsitos.e.da.natureza.da.conta.depsito" : "english example",
		"label.declarao.fatca/crs" : "english example",
		"label.declarar.residncia" : "english example",
		"label.sem.renda" : "Without income",
		"label.descrio.da.atividade" : "english example",
		"label.deseja.receber.informaes.do.carto.de.crdito.caixa?" : "english example",
		"label.deslogar" : "english example",
		"label.dia.do.dbito" : "english example",
		"label.dia.do.vencimento.da.fatura" : "english example",
		"label.digitalizao.comp.renda.aberto" : "english example",
		"label.digitalizao.comp.renda.fechado" : "english example",
		"label.digitalizao.comp.residncia.aberto" : "english example",
		"label.digitalizao.comp.residncia.fechado" : "english example",
		"label.digitalizao.de.documentos" : "english example",
		"label.digitalizao.doc.identificao.aberto" : "english example",
		"label.digitalizao.doc.identificao.fechado" : "english example",
		"label.digitalizar" : "english example",
		"label.documento.de.identificacao" : "Identification document",
		"label.documento.de.residencia" : "Residence document",
		"label.documento.de.renda" : "Income document",
		"label.dossi.digital" : "english example",
		"label.dossi.digital.atualizacao.finalizada" : "Update completed", 
		"label.dossi.digital.consulta" : "The customer's Digital Dossier is available for consultation",
		"label.dossi.digital.do.cliente" : "english example",
		"label.dossie.-.dossi.digital" : "english example",
		"label.email:.usuario@email.com.br.-.data.de.referncia:.dd/mm/aaaa.[excluir]" : "english example",
		"label.email.do.usurio" : "english example",
		"label.endereo.comercial" : "english example",
		"label.endereo.para.entrega.da.fatura" : "english example",
		"label.entrada.de.cnpj" : "english example",
		"label.entrada.de.combo" : "english example",
		"label.entrada.de.cpf" : "english example",
		"label.entrada.de.data.(calendrio.popup)" : "english example",
		"label.entrada.de.data.(calendrio)" : "english example",
		"label.entrada.de.email" : "english example",
		"label.entrada.de.moeda.brasileira" : "english example",
		"label.entrada.de.nmero" : "english example",
		"label.entrada.de.opes.(radio)" : "english example",
		"label.entrada.de.senha" : "english example",
		"label.entrada.de.telefone" : "english example",
		"label.entrada.de.texto" : "english example",
		"label.entrada.de.verificao.(checkbox)" : "english example",
		"label.entrada.do.cep" : "english example",
		"label.entrar" : "english example",
		"label.enviar.documentos.por.email" : "english example",
		"label.enviar.nova.senha" : "english example",
		"label.esqueci.a.senha" : "english example",
		"label.esqueci.minha.senha" : "english example",
		"label.estado.civil" : "english example",
		"label.exibir" : "english example",
		"label.exibe.a.situao.atual.da.assinatura.de.notificaes" : "english example",
		"label.exibir.documento" : "english example",
		"label.finalidade" : "english example",
		"label.formulrios" : "english example",
		"label.gostaria.de.receber.mais.informaes.sobre.produtos.e.servios.da.caixa?" : "english example",
		"label.grau.de.instruo" : "english example",
		"label.ícone" : "english example",
		"label.identificacao.do.cliente.conferida" : "english example",
		"label.impresso.para.conferncia" : "english example",
		"label.imprimir" : "english example",
		"label.imprimir.documentos.contratuais" : "english example",
		"label.incluir" : "english example",
		"label.informaes.do.cliente" : "english example",
		"label.informaes.do.cliente.conta.conjunta" : "english example",
		"label.informaes.do.cliente.e.parmetros.da.conta" : "english example",
		"label.informaes.do.cliente.procurador.tutor.curador" : "english example",
		"label.informaes.patrimoniais" : "english example",
		"label.informe.a.assinatura.do.cliente" : "english example",
		"label.informe.a.data.de.dbito.(juros)" : "english example",
		"label.informe.a.senha" : "english example",
		"label.informe.o.bairro" : "english example",
		"label.informe.o.cep" : "english example",
		"label.informe.o.cnpj" : "english example",
		"label.informe.o.cpf" : "english example",
		"label.informe.o.cpf.do.cnjuge" : "english example",
		"label.informe.o.email" : "english example",
		"label.informe.o.email.cadastrado" : "english example",
		"label.informe.o.endereo.comercial" : "english example",
		"label.informe.o.logradouro" : "english example",
		"label.informe.o.nmero" : "english example",
		"label.informe.o.nmero.tin" : "english example",
		"label.informe.o.nome" : "english example",
		"label.informe.o.nome.completo" : "english example",
		"label.informe.o.nome.da.cidade" : "english example",
		"label.informe.o.nome.da.fonte.pagadora" : "english example",
		"label.informe.o.nome.do.contato" : "english example",
		"label.informe.o.nome.do.pai" : "english example",
		"label.informe.o.telefone" : "english example",
		"label.informe.o.valor.da.renda.bruta" : "english example",
		"label.informe.o.valor.da.renda.lquida" : "english example",
		"label.informe.o.valor.do.imposto.retido.na.fonte" : "english example",
		"label.informe.o.valor.em.real" : "english example",
		"label.informe.o.valor.em.real.do.limite.contratado" : "english example",
		"label.limite.contratado" : "english example",
		"label.limite.de:.r$1.000,00" : "english example",
		"label.limite.disponvel:.r$5.000,00" : "english example",
		"label.limite.disponvel:.r$8.000,00" : "english example",
		"label.link" : "english example",
		"label.listagem" : "english example",
		"label.localizar.cliente" : "english example",
		"label.login" : "english example",
		"label.logradouro" : "english example",
		"label.maria.zilda.pagotti./.cpf:.000.399.368-05" : "english example",
		"label.meios.de.comunicao" : "english example",
		"label.menor.emancipado" : "english example",
		"label.modalidade" : "english example",
		"label.modalidade.da.cesta" : "english example",
		"label.nacionalidade" : "english example",
		"label.naturalidade" : "english example",
		"label.nmero" : "english example",
		"label.nmero.da.conta:.00095231-0" : "english example",
		"label.nmero.da.conta.99999-9" : "english example",
		"label.nmero.tin" : "english example",
		"label.nome" : "english example",
		"label.nome:.maria.zilda.pagotti" : "english example",
		"label.nome:.maria.zilda.pagotti./.cpf:.000.399.368-05" : "english example",
		"label.nome.do.cnjuge" : "english example",
		"label.nome.da.fonte.pagadora" : "english example",
		"label.nome.da.me:.maria.josé.de.oliveira" : "english example",
		"label.nome.da.me:.nilza.cesar" : "english example",
		"label.nome.do.cliente:.vagner.de.paulo" : "english example",
		"label.nome.do.pai" : "english example",
		"label.novo.usurio" : "english example",
		"label.ocultar.documento" : "english example",
		"label.ocupao" : "english example",
		"label.operao:.001.-.conta.corrente.pf" : "english example",
		"label.operao.comercial" : "english example",
		"label.opes" : "english example",
		"label.pacote.desconto.cesta.de.servios" : "english example",
		"label.padaria.dois.garotos.-.agente.administrativo.-.r$18.000,00" : "english example",
		"label.parabns,.voc.j.pode.contratar.o.produto!" : "english example",
		"label.parmetros.da.conta" : "english example",
		"label.perfil" : "english example",
		"label.perfil.do.usurio" : "english example",
		"label.pesquisa.cadastral" : "english example",
		"label.pesquisas.cadastrais" : "english example",
		"label.por.favor,.digitalize.os.seguintes.documentos:" : "english example",
		"label.por.favor.informe.seu.login" : "english example",
		"label.portflio.de.acessos" : "english example",
		"label.possui" : "english example",
		"label.prestao.mxima.admitida" : "english example",
		"label.primo/siogp" : "english example",
		"label.principal" : "english example",
		"label.procurador(es)" : "english example",
		"label.produtos.ativos" : "english example",
		"label.produtos.do.cliente" : "english example",
		"label.profisso:.bancário.e.economiário" : "english example",
		"label.profisso/.cdigo.da.ocupao" : "english example",
		"label.programa.pontos.caixa?" : "english example",
		"label.prototipado.no.primo,.suportado.pelo.siogp" : "english example",
		"label.pv.responsvel:.0002" : "english example",
		"label.quadro.de.valores" : "english example",
		"label.quebra.de.linha.(br)" : "english example",
		"label.quero.me.cadastrar" : "english example",
		"label.receber.emails" : "english example",
		"label.receber.notificaes" : "english example",
		"label.redigitao.senha" : "english example",
		"label.renda.bruta" : "english example",
		"label.renda.comprovada" : "english example",
		"label.renda.lquida" : "english example",
		"label.renda.no.comprovada/informal" : "english example",
		"label.renda.total:.r$1.000,00" : "english example",
		"label.responsabilizo-me.pela.exatido.das.informaes.prestadas,..vista.dos.originais.do.documento.de.identidade,.do.cpf.e.outros.comprobatrios.dos.demais.elementos.de.informao.apresentados,.sob.pena.de.aplicao.do.disposto.no.artigo.64,.da.lei.nº.8.383,.de.30/12/1991." : "english example",
		"label.resultado.da.abertura.da.conta.e.contratao.de.servios" : "english example",
		"label.resultado.da.digitalizao.de.documentos" : "english example",
		"label.resumo.do.cliente" : "english example",
		"label.retornar" : "english example",
		"label.rg" : "english example",
		"label.roteiro.negocial" : "english example",
		"label.saques,.transferncias,.pagamentos,.agendamentos.a.partir.de" : "english example",
		"label.selecione.a.data.de.admisso" : "english example",
		"label.selecione.a.data.de.nascimento.do.cnjuge" : "english example",
		"label.selecione.a.opo" : "english example",
		"label.selecione.as.opes" : "english example",
		"label.selecione.o.item" : "english example",
		"label.selecione.o.dispositivo" : "Select device",
		"label.selecione.o.tipo.de.carto" : "english example",
		"label.sem.rendas.no.comprovadas/informais" : "english example",
		"label.senha" : "english example",
		"label.senha.da.conta.gerada.com.sucesso" : "english example",
		"label.separador.(hr)" : "english example",
		"label.servio.de.mensagens.via.celular" : "english example",
		"label.servios.do.carto" : "english example",
		"label.sexo" : "english example",
		"label.sicow:.problema.na.consulta" : "english example",
		"label.sinad:.problema.na.consulta" : "english example",
		"label.situao:.regular" : "english example",
		"label.situao.das.notificaes" : "english example",
		"label.sobre" : "english example",
		"label.solicitar.avaliao" : "english example",
		"label.solidria" : "english example",
		"label.splash" : "english example",
		"label.sub-ttulo" : "english example",
		"label.tabela.filtro.por.colunas" : "english example",
		"label.tela.de.cadastramento" : "english example",
		"label.tela.de.login" : "english example",
		"label.tela.de.perfil.do.usurio" : "english example",
		"label.tela.de.recuperao.de.senha" : "english example",
		"label.tela.de.splash" : "english example",
		"label.tela.principal" : "english example",
		"label.telefone./.comum.-.residencial.atual.-.(11).97644-8667" : "english example",
		"label.telefone.fixo:.(021).9999-9999.-.data.de.referncia.dd/mm/aaaa.[excluir]" : "english example",
		"label.termo.de.declarao" : "english example",
		"label.texto" : "english example",
		"label.timer" : "english example",
		"label.tipo.de.carto" : "english example",
		"label.tipo.de.conta" : "english example",
		"label.tipo.de.conta.0001-.conta.corrente" : "english example",
		"label.tipo.de.fonte.pagadora" : "english example",
		"label.tipo.de.logradouro" : "english example",
		"label.titular:.vagner.de.paulo" : "english example",
		"label.titular.(es)" : "english example",
		"label.titular(es)" : "english example",
		"label.trocar.a.senha" : "english example",
		"label.ttulo" : "english example",
		"label.tutor(es)" : "english example",
		"label.uf" : "english example",
		"label.v1.0" : "english example",
		"label.valor.do.imposto.retido.na.fonte" : "english example",
		"label.variante" : "english example",
		"label.voltar" : "english example",
		"label.data.invalid" : "Invalid Date",
		"label.campo.obrigatorio" : "Required field",
		'label.processando' : 'Processing...',
		'titulo.cancelar.atendimento' : 'Cancelar Atendimento',
		'label.deseja.cancelar.atendimento' : 'Deseja cancelar o atendimento?',
		'label.tipo' : 'Tipo',
		'label.naturalidade.uf' : 'Naturalidade UF',
		'label.naturalidade.municipio' : 'Naturalidade Município',
		'titulo.incluir.funcao' : 'Incluir Função',
		'titulo.excluir.funcao' : 'Excluir Função',
		'tooltip.dados.declarados.logradouro' : 'Example: Rio Branco nº 174, 7º andar, Centro',
		'tooltip.dados.declarados.cep' : 'Search Zip Code',
		'tooltip.dados.declarados.tipo.logradouro' : 'Examples: Street, Av, QD etc. Maximum of 3 positions',
		'tooltip.dados.declarados.uf' : 'INITIALS format is XX',
		'tooltip.dados.declarados.valor.total.patrimonio' : 'Enter total declared value by customer',
		'tooltip.dados.declarados.senha.eletronica' : 'Password generated by the client on the signature card',
		"label.dispositivo" : 'Devices',
		"label.selecione" : 'Select'
		
	});
	$translateProvider.translations('pt', {
		'label.sucesso' : 'Sucesso',
		'label.falha.listar.controller' : 'Falha ao listar ',
		'label.falha.incluir.controller' : 'Falha ao incluir ',
		'label.falha.verificar.inscricao' : 'Falha ao efetuar a verificação da inscrição de recebimento de email',
		'label.aplicacao.restrita.informe.email' : 'Aplicação restrita, informe o email',
		'label.aplicacao.restrita.informe.codigo.acesso' : 'Aplicação restrita, informe o código de acesso',
		'label.codigo.acesso.autorizado.contate.responsavel.projeto' : 'Código de acesso não autorizado, contate o responsável pelo projeto',
		'label.atencao' : 'Atenção!',
		'label.funcionou' : 'Funcionou!',
		'label.invalido' : 'Inválido.',
		'label.cliente' : 'Cliente',
		'label.vazio' : 'Vazio!',
		'label.upload.realizado.com.sucesso' : 'Upload realizado com sucesso',
		'label.selecione.algum.arquivo.para.upload' : 'Selecione algum arquivo para upload',
		'label.api.arquivos.nao.suportadas.neste.navegador' : 'As APIs de arquivos não são totalmente suportadas neste navegador.',
		'label.assinatura.efetuada.com.sucesso' : 'Assinatura efetuada com sucesso',
		'label.falha.ao.efetuar.assinatura' : 'Falha ao efetuar assinatura',
		'label.cancelamento.efetuado.com.sucesso' : 'Cancelamento efetuado com sucesso',
		'label.assinatura.recebimento.email.realizada.com.sucesso' : 'Assinatura para recebimento de email realizada com sucesso',
		'label.falha.efetuar.inscricao.recebimento.email' : 'Falha ao efetuar a inscrição para recebimento de email',
		'label.cancelamento.recebimento.email.realizado.sucesso' : 'Cancelamento do recebimento de email realizado com sucesso',
		'label.falha.efetuar.cancelamento.recebimento.email' : 'Falha ao efetuar o cancelamento do recebimento de email',
		'label.modo.desenvolvimento' : 'Modo Desenvolvimento',
		'label.informe.codigo.desenvolvimento' : 'Informe o código de desenvolvimento',
		'label.exclusao.confirmada.pelo.usuario' : 'Exclusão confirmada pelo usuário',
		'label.exclusao.cancelada.pelo.usuario' : 'Exclusão cancelada pelo usuário',
		'label.confirma.exclusao.deste.item' : 'Confirma a exclusão deste item?',
		'label.navegacao.suspensa.click.ok' : 'Navegação suspensa durante a edição. Clique em OK para prosseguir',
		'label.sua.opiniao.foi.enviada.com.sucesso' : 'Sua opinião foi enviada com sucesso! Obrigado por participar',
		'label.faltou.avaliar.quesito' : 'Faltou avaliar o quesito ',
		'label.nome.da.mensagem' : 'Nome da mensagem',
		'label.titulo.da.mensagem' : 'Título da mensagem',
		'label.conteudo.da.mensagem' : 'Conteúdo da mensagem',
		'label.confirma.remover.esta.acao' : 'Confirma remover esta ação?',
		'label.informe.o.nome2' : 'Informe o nome',
		'label.informe.o.titulo' : 'Informe o Título',
		'label.informe.a.mensagem' : 'Informe a Mensagem',
		'label.titulo.do.email' : 'Titulo do Email',
		'label.titulo.a.mensagem' : 'Título da mensagem',
		'label.conteudo.a.mensagem' : 'Conteúdo da mensagem',
		'label.sua.mensagem.foi.enviada.com.sucesso' : 'Sua mensagem foi enviada com sucesso!',
		'label.informe.o.titulo.do.email' : 'Informe o título do email',
		'label.informe.a.mensagem.do.email' : 'Informe a mensagem do email',
		'label.adicione.um.destinatario' : 'Adicione um destinatário',
		'label.clique.aqui.para.finalizarAtendimento': 'Clique Aqui Para Finalizar o Atendimento',
		'label.finalizarAtendimento': 'Finalizar Atendimento',
		'label.erro.alteracao.limite': 'Alteração do campo além do limite',
		
		'label.informe.o.cep.residencial': 'Informe o CEP Residencial',
		'label.informe.o.tipo.logradouro.residencial': 'Informe o Tipo Logradouro Residencial',
		'label.informe.o.logradouro.residencial': 'Informe o Logradouro Residencial',
		'label.informe.o.numero.residencial': 'Informe o Número Residencial',
		'label.informe.o.complemento.residencial': 'Informe o Complemento Residencial',
		'label.informe.o.bairro.residencial': 'Informe o Bairro Residencial',
		'label.informe.o.uf.residencial': 'Informe o UF Residencial',
		'label.informe.o.cidade.residencial': 'Informe a Cidade da Residencia',
		'label.informe.o.nome.social': 'Informe o Nome Social',
		'label.informe.o.cep.comercial': 'Informe o CEP Comercial',
		'label.informe.o.tipo.logradouro.comercial': 'Informe o Tipo Logradouro Comercial',
		'label.informe.o.logradouro.comercial': 'Informe o Logradouro Comercial',
		'label.informe.o.numero.comercial': 'Informe o Número Comercial',
		'label.informe.o.complemento.comercial': 'Informe o Complemento Comercial',
		'label.informe.o.bairro.comercial': 'Informe o Bairro Comercial',
		'label.informe.o.uf.comercial': 'Informe o UF Comercial',
		'label.informe.o.cidade.comercial': 'Informe a Cidade do Comércio',
		'label.endereco.residencial': 'Endereço Residencial',
		'label.dados.pessoais': 'Dados Pessoais',
		'label.endereco.comercial': 'Endereço Comercial',
		'label.nome.social': 'Nome Social',
		'label.numero': 'Número',
		'label.selecione.celular' : 'Selecione o Celular',
		'estadoCivil' : 'Estado Civil: Campo Obrigatório',
		'naturalidadeMunicipio':'Naturalidade Município: Campo Obrigatório',
		'naturalidadeUf':'Naturalidade UF: Campo Obrigatório',
		'valorTotalPatrimonio' : 'Valor Patrimônio: Campo Obrigatório',
		'cepResidencial' : 'Cep Residencial: Campo Obrigatório',
		'tipoLogradouroResidencial' : 'Tipo Logradouro Residencial: Campo Obrigatório',
		'logradouroResidencial' : 'Logradouro Residencial: Campo Obrigatório',
		'bairroResidencial' : 'Bairro Residencial: Campo Obrigatório',
		'numeroResidencial' : 'Número Residencial: Campo Obrigatório',
		'cidadeResidencial' : 'Cidade Residencial: Campo Obrigatório',
		'complementoResidencial' : 'Complemento Residencial: Campo Obrigatório',
		'ufResidencial' : 'UF Residencial: Campo Obrigatório',
		'sexo' : 'Sexo: Campo Obrigatório',
		'grauInstrucao' : 'Grau Instrução: Campo Obrigatório',
		'codigoOcupacao' : 'Profissão: Campo Obrigatório',
		'numCpfdoconjuge' : 'Cpf do Cônjuge: Campo Obrigatório',
		'conjugeNome' : 'Nome do Cônjuge: Campo Obrigatório',
		'dataNascimento' : 'Data Nascimento do Cônjuge: Campo Obrigatório',
		'numTelefone': 'Número de Telefone: Campo Obrigatório',
		'numeroTin' : 'Número TIN : Campo Obrigatório',
		'declaracaoFatcaCrs' : 'Escolha uma opção de Declaração FATCA ou CRS',
		'declaracaoCrs' : 'Declaracao CRS : Campo Obrigatório!',
		'declaracaoProposito' : 'Declaração de Propósitos e da natureza : Campo Obrigatório',
		'label.fechar' : 'Fechar',
		'label.abrir' : 'Abrir',
		'label.enviar' : 'Enviar',
		'label.deixe.aqui.suas.criticas.sugestoes' : 'Deixe aqui suas críticas ou sugestões (opcional)',
		'label.ajude.melhorar.esta.aplicacao.enviando.opiniao' : 'Ajude-nos a melhorar esta aplicação enviando sua opinião',
		'label.avaliacao.usuario' : 'Avaliação do usuário',
		'label.gostaria.receber.notificacoes.central.caixa' : 'Gostaria de receber notificações da Central Caixa?',
		'label.sim.eu.quero' : 'Sim, eu quero!',
		'label.nao.obrigado' : 'Não obrigado.',
		'label.nao.receber.emails' : 'NÃO RECEBER EMAILS',
		'label.clique.para.cancelar.recebimento.emails' : 'Clique para cancelar o recebimento de emails',
		'label.receber.email' : 'RECEBER EMAILS',
		'label.clique.para.assinar.canal.recebimento.emails' : 'Clique para assinar o canal o recebimento de emails',
		'label.ir.para.conteudo' : 'Ir para o conteúdo (ALT + 1)',
		'label.ir.para.menu' : 'Ir para o menu (ALT + 2)',
		'label.informe.o.patrimonio' : 'Informe o Patrimônio',
		'label.informe.o.valor.expresso' : 'Valor total expresso (R$)',
		"label." : "",
		"label.." : " ",
		"label.1.000.399.368-05.maria.zilda.pagotti" : "1 000.399.368-05 MARIA ZILDA PAGOTTI",
		"label.1.999.999.999-99.fulano.de.tal" : "1 999.999.999-99 FULANO DE TAL",
		"label.2.132.120.827-80.fulano.de.tal" : "2 132.120.827-80 FULANO DE TAL",
		"label.abertura.conta.dossi.digital" : "Abertura Conta Dossiê Digital",
		"label.abertura.de.conta" : "ABERTURA DE CONTA",
		"label.abertura.de.conta.dossi.digital" : "Abertura de Conta Dossiê Digital",
		"label.abertura.de.conta.resultado" : "ABERTURA DE CONTA RESULTADO",
		"label.abrir.conta/contratar.servios" : "Abrir Conta/Contratar Serviços",
		"label.adeso..servios" : "Adesão à Serviços",
		"label.agncia:.0002.-.planalto,.df" : "Agência: 0002 - Planalto, DF",
		"label.agncia:.0002.-.planalto,df" : "Agência: 0002 - Planalto,DF",
		"label.aprovao.da.abertura.de.conta" : "Aprovação da Abertura de Conta",
		"label.aprovao.do.cadastro" : "Aprovação do Cadastro",
		"label.aprovar" : "Aprovar",
		"label.assinatura.do.cliente" : "Assinatura do Cliente",
		"label.assinatura.do.gerente" : "ASSINATURA DO GERENTE",
		"label.assinatura.do.gerente.final" : "ASSINATURA DO GERENTE FINAL",
		"label.assinatura.eletrnica" : "Assinatura Eletrônica",
		"label.atualizar" : "Atualizar",
		"label.atualizar.cnh" : "Atualizar CNH",
		"label.atualizar.rg" : "Atualizar RG",
		"label.autoriza.o.envio.de.informaes.do.fgts?" : "Autoriza o envio de informações do FGTS?",
		"label.autorizao.documental" : "AUTORIZAÇÃO DOCUMENTAL",
		"label.autorizao.nº.0123456783" : "Autorização nº 0123456783",
		"label.avaliaes.vlidas.-.siric" : "Avaliações Válidas - SIRIC",
		"label.avaliao.de.risco" : "AVALIAÇÃO DE RISCO",
		"label.avaliao.de.risco.-.cliente.comercial" : "Avaliação de Risco - Cliente Comercial",
		"label.avaliao.de.risco.-.operao.comercial" : "Avaliação de Risco - Operação Comercial",
		"label.avaliao.de.risco.cliente.comercial" : "AVALIAÇÃO DE RISCO CLIENTE COMERCIAL",
		"label.avaliao.de.risco.operao" : "AVALIAÇÃO DE RISCO OPERAÇÃO",
		"label.avaliar.op..crdito" : "Avaliar Op. Crédito",
		"label.bairro" : "Bairro",
		"label.bandeira" : "Bandeira",
		"label.boto" : "Botão",
		"label.boto.imagem" : "Botão Imagem",
		"label.cadastramento.da.senha.do.cliente" : "Cadastramento da Senha do Cliente",
		"label.cadastramento.de.senha.cliente" : "CADASTRAMENTO DE SENHA CLIENTE",
		"label.cadastrar" : "Cadastrar",
		"label.cadastro" : "CADASTRO",
		"label.cadastro.de.assinatura.eletrnica.no.pde.ser.efetuado" : "Cadastro de assinatura eletrônica não pôde ser efetuado",
		"label.caixa.de.texto" : "Caixa de Texto",
		"label.caixa.seguros" : "CAIXA SEGUROS",
		"label.cancelar" : "Cancelar",
		"label.cancelar.emails" : "Cancelar Email's",
		"label.cancelar.notificaes" : "Cancelar Notificações",
		"label.cargo.do.funcionrio" : "Cargo do Funcionário",
		"label.carregando..." : "Carregando...",
		"label.carto.assinatura" : "Cartão Assinatura",
		"label.cedesrj.-.caixa.econmica.federal" : "CEDESRJ - Caixa Econômica Federal",
		"label.celular:.(011).99999-9999.-.data.de.referncia.dd/mm/aaaa.[excluir]" : "Celular: (011) 99999-9999 - Data de Referência DD/MM/AAAA [Excluir]",
		"label.cep" : "CEP",
		"label.cesta.de.servios" : "Cesta de Serviços",
		"label.cheque.especial.implantado.com.sucesso" : "Cheque Especial implantado com sucesso",
		"label.cidade" : "Cidade",
		"label.cidade/uf,.dd.de.mm.de.aaaa" : "Cidade/UF, dd de mm de aaaa",
		"label.cliente.comercial" : "Cliente Comercial",
		"label.clique.aqui.para" : "Clique aqui para",
		"label.clique.aqui.para.abrir.conta/contratar.servios" : "Clique aqui para Abrir Conta/Contratar Serviços",
		"label.clique.aqui.para.aprovar" : "Clique aqui para aprovar",
		"label.clique.aqui.para.atualizar" : "Clique aqui para atualizar",
		"label.clique.aqui.para.avaliar.op..crdito" : "Clique aqui para Avaliar Op. Crédito",
		"label.clique.aqui.para.cancelar" : "Clique aqui para cancelar",
		"label.clique.aqui.para.consultar" : "Clique aqui para consultar",
		"label.clique.aqui.para.continuar" : "Clique aqui para continuar",
		"label.clique.aqui.para.digitalizar" : "Clique aqui para digitalizar",
		"label.clique.aqui.para.exibir.documento" : "Clique aqui para exibir documento",
		"label.clique.aqui.para.imprimir.documentos.contratuais" : "Clique aqui para Imprimir Documentos Contratuais",
		"label.clique.aqui.para.incluir" : "Clique aqui para incluir",
		"label.clique.aqui.para.ir.para.cliente.comercial" : "Clique aqui para ir para cliente comercial",
		"label.clique.aqui.para.localizar.cliente" : "Clique aqui para Localizar Cliente",
		"label.clique.aqui.para.não.receber.emails" : "Clique aqui para NÃO receber email's",
		"label.clique.aqui.para.não.receber.notificaes" : "Clique aqui para NÃO receber notificações",
		"label.clique.aqui.para.ocultar.documento" : "Clique aqui para ocultar documento",
		"label.clique.aqui.para.receber.emails" : "Clique aqui para receber Email's",
		"label.clique.aqui.para.receber.notificaes" : "Clique aqui para receber notificações",
		"label.clique.aqui.para.visualizar.o.comprovante.de.identificao" : "Clique aqui para visualizar o Comprovante de Identificação",
		"label.clique.aqui.para.visualizar.o.comprovante.de.rendimento" : "Clique aqui para visualizar o Comprovante de Rendimento",
		"label.clique.aqui.para.visualizar.o.comprovante.de.residncia" : "Clique aqui para visualizar o Comprovante de Residência",
		"label.clique.aqui.para.voltar" : "Clique aqui para voltar",
		"label.clique.para.cadastrar" : "Clique para cadastrar",
		"label.clique.para.cadastrar.nova.senha" : "Clique para cadastrar nova senha",
		"label.clique.para.cadastrar.um.novo.usurio" : "Clique para cadastrar um novo usuário",
		"label.clique.para.deslogar" : "Clique para deslogar",
		"label.clique.para.enviar.nova.senha" : "Clique para enviar nova senha",
		"label.clique.para.instalar.a.verso.mobile" : "Clique para instalar a versão Mobile",
		"label.clique.para.logar" : "Clique para logar",
		"label.clique.para.retornar" : "Clique para retornar",
		"label.clique.para.trocar.a.senha" : "Clique para trocar a Senha",
		"label.cnh" : "CNH",
		"label.cnpj" : "CNPJ",
		"label.cocli.da.fonte.pagadora" : "COCLI da fonte pagadora",
		"label.complemento" : "Complemento",
		"label.compras.com.carto.de.dbito.a.partir.de" : "Compras com cartão de débito a partir de",
		"label.comprovante.de.renda" : "Comprovante de Renda",
		"label.comprovante.de.residncia" : "Comprovante de Residência",
		"label.concorda.em.participar.de.campanhas.de.incentivo.da.caixa.com.premiao?" : "Concorda em participar de campanhas de Incentivo da CAIXA com premiação?",
		"label.confirmar.a.senha" : "Confirmar a senha",
		"label.consulta.avaliaes.vlidas" : "CONSULTA AVALIAÇÕES VÁLIDAS",
		"label.consulta.avaliaes.vlidas.aprovadas" : "CONSULTA AVALIAÇÕES VÁLIDAS APROVADAS",
		"label.consultar" : "Consultar",
		"label.conta.aberta.com.sucesso" : "Conta aberta com sucesso",
		"label.contato" : "Contato",
		"label.contatos:.telefone./.comum.-.residencial.atual.-.(61).3206-7676" : "Contatos: Telefone / Comum - Residencial Atual - (61) 3206-7676",
		"label.continuar" : "Continuar",
		"label.contrata.seguro.do.carto?" : "Contrata Seguro do Cartão?",
		"label.contratao.de.produtos" : "Contratação de Produtos",
		"label.contratao.de.servios.de.mensagem.via.celular.no.pde.ser.efetuada" : "Contratação de Serviços de Mensagem via celular não pôde ser efetuada",
		"label.correio.eletrnico.(email):.teste@teste.com.br" : "Correio Eletrônico (email): teste@teste.com.br",
		"label.cpf" : "CPF",
		"label.datanascimento" : "Data de Nascimento",
		"label.cpf:.000.399.368-05" : "CPF: 000.399.368-05",
		"label.dados.conjuge" : "Dados do Cônjuge",
		"label.cpf.do.cnjuge" : "CPF do Cônjuge",
		"label.cpf.do.cliente:.132.120.827-80" : "CPF do Cliente: 132.120.827-80",
		"label.cpf.do.responsvel:.999.999.999-99" : "CPF do Responsável: 999.999.999-99",
		"label.cpf.informado.est.com.situao.regular.perante.a.receita.federal." : "CPF informado está com situação REGULAR perante a Receita Federal.",
		"label.curador(es)" : "Curador(es)",
		"label.dados.da.conta" : "Dados da Conta",
		"label.dados.declarados" : "Dados Declarados",
		"label.prezado.cliente.insira.assinatura": "Prezado cliente, insira sua assinatura eletrônica",
		"label.dados.do.titular" : "Dados do Titular",
		"label.dados.do(s).titular(es)" : "Dados do(s) Titular(es)",
		"label.data.de.admisso/incio" : "Data de admissão/início",
		"label.data.de.cadastramento" : "Data de Cadastramento",
		"label.data.de.dbito.(juros)" : "Data de Débito (Juros)",
		"label.data.de.nascimento:.21/03/1956" : "Data de nascimento: 21/03/1956",
		"label.data.de.nascimento:.27/04/1958" : "Data de Nascimento: 27/04/1958",
		"label.data.de.nascimento:.27/04/1988" : "Data de Nascimento: 27/04/1988",
		"label.data.de.nascimento.do.cnjuge" : "Data de Nascimento do Cônjuge",
		"label.ddd.e.nmero" : "DDD e Número",
		"label.declaracoes" : "Declarações",
		"label.declarao.de.dados" : "DECLARAÇÃO DE DADOS",
		"label.declarao.de.propsitos.e.da.natureza.da.conta.depsito" : "Declaração de Propósitos e da natureza da conta depósito",
		"label.declarao.fatca/crs" : "Declaração FATCA/CRS",
		"label.fatca" : "FATCA",
		"label.crs" : "CRS",
		"label.declarar.residncia" : "Declarar Residência",
		"label.sem.renda" : "Sem Renda",
		"label.descrio.da.atividade" : "Descrição da Atividade",
		"label.codigo.tipo.situacao": "Código / Descrição / Tipo de Pessoa / Situação",
		"label.deseja.receber.informaes.do.carto.de.crdito.caixa?" : "Deseja receber informações do cartão de crédito CAIXA?",
		"label.deslogar" : "Deslogar",
		"label.dia.do.dbito" : "Dia do Débito",
		"label.dia.do.vencimento.da.fatura" : "Dia do Vencimento da Fatura",
		"label.digitalizao.comp.renda.aberto" : "DIGITALIZAÇÃO COMP RENDA ABERTO",
		"label.digitalizao.comp.renda.fechado" : "DIGITALIZAÇÃO COMP RENDA FECHADO",
		"label.digitalizao.comp.residncia.aberto" : "DIGITALIZAÇÃO COMP RESIDÊNCIA ABERTO",
		"label.digitalizao.comp.residncia.fechado" : "DIGITALIZAÇÃO COMP RESIDÊNCIA FECHADO",
		"label.digitalizao.de.documentos" : "DIGITALIZAÇÃO DE DOCUMENTOS",
		"label.digitalizao.doc.identificao.aberto" : "DIGITALIZAÇÃO DOC IDENTIFICAÇÃO ABERTO",
		"label.digitalizao.doc.identificao.fechado" : "DIGITALIZAÇÃO DOC IDENTIFICAÇÃO FECHADO",
		"label.digitalizar" : "Digitalizar",
		"label.documento.de.identificacao" : "Documento de identificação",
		"label.documento.de.residencia" : "Documento de residência",
		"label.documento.de.renda" : "Documento de renda",
		"label.dossi.digital" : "Dossiê Digital",
		"label.dossi.digital.atualizacao.finalizada" : "Atualização finalizada",
		"label.dossi.digital.consulta" : "O Dossiê Digital do cliente encontra-se disponível para consulta.",
		"label.dossi.digital.do.cliente" : "Dossiê Digital do Cliente",
		"label.dossie.-.dossi.digital" : "DOSSIE - Dossiê Digital",
		"label.email:.usuario@email.com.br.-.data.de.referncia:.dd/mm/aaaa.[excluir]" : "Email: usuario@email.com.br - Data de Referência: DD/MM/AAAA [Excluir]",
		"label.email.do.usurio" : "Email do usuário",
		"label.endereo.comercial" : "Endereço Comercial",
		"label.endereo.para.entrega.da.fatura" : "Endereço para Entrega da Fatura",
		"label.entrada.de.cnpj" : "Entrada de CNPJ",
		"label.entrada.de.combo" : "Entrada de Combo",
		"label.entrada.de.cpf" : "Entrada de CPF",
		"label.entrada.de.data.(calendrio.popup)" : "Entrada de Data (calendário popup)",
		"label.entrada.de.data.(calendrio)" : "Entrada de Data (calendário)",
		"label.entrada.de.email" : "Entrada de Email",
		"label.entrada.de.moeda.brasileira" : "Entrada de Moeda Brasileira",
		"label.entrada.de.nmero" : "Entrada de Número",
		"label.entrada.de.opes.(radio)" : "Entrada de Opções (radio)",
		"label.entrada.de.senha" : "Entrada de Senha",
		"label.entrada.de.telefone" : "Entrada de Telefone",
		"label.entrada.de.texto" : "Entrada de Texto",
		"label.entrada.de.verificao.(checkbox)" : "Entrada de Verificação (checkbox)",
		"label.entrada.do.cep" : "Entrada do CEP",
		"label.entrar" : "Entrar",
		"label.enviar.documentos.por.email" : "Enviar Documentos por Email",
		"label.enviar.nova.senha" : "Enviar nova senha",
		"label.esqueci.a.senha" : "Esqueci a senha",
		"label.esqueci.minha.senha" : "ESQUECI MINHA SENHA",
		"label.estado.civil" : "Estado Civil",
		"label.excluir" : "Excluir",
		"label.exibir" : "Exibir",
		"label.exibe.a.situao.atual.da.assinatura.de.notificaes" : "Exibe a situação atual da assinatura de notificações",
		"label.exibir.documento" : "Exibir Documento",
		"label.finalidade" : "Finalidade",
		"label.formulrios" : "Imprimir formulários para conferência",
		"label.gostaria.de.receber.mais.informaes.sobre.produtos.e.servios.da.caixa?" : "Gostaria de receber mais informações sobre produtos e serviços da CAIXA?",
		"label.grau.de.instruo" : "Grau de Instrução",
		"label.ícone" : "Ícone",
		"label.identificacao.do.cliente.conferida" : "Identificação do cliente conferida",
		"label.impresso.para.conferncia" : "Impressão para Conferência",
		"label.imprimir" : "Imprimir",
		"label.imprimir.documentos.contratuais" : "Imprimir Documentos Contratuais",
		"label.incluir" : "Incluir",
		"label.informaes.do.cliente" : "Informações do Cliente",
		"label.informaes.do.cliente.conta.conjunta" : "INFORMAÇÕES DO CLIENTE CONTA CONJUNTA",
		"label.informaes.do.cliente.e.parmetros.da.conta" : "INFORMAÇÕES DO CLIENTE E PARÂMETROS DA CONTA",
		"label.informaes.do.cliente.procurador.tutor.curador" : "INFORMAÇÕES DO CLIENTE PROCURADOR TUTOR CURADOR",
		"label.informaes.patrimoniais" : "Informações Patrimoniais",
		"label.informe.a.assinatura.do.cliente" : "Informe a Assinatura do Cliente",
		"label.informe.a.data.de.dbito.(juros)" : "Informe a data de débito (juros)",
		"label.informe.a.senha" : "Informe a senha",
		"label.informe.o.bairro" : "Informe o bairro",
		"label.informe.o.cep" : "Informe o cep",
		"label.informe.o.cnpj" : "Informe o CNPJ",
		"label.informe.o.cpf" : "Informe o cpf",
		"label.informe.o.cpf.do.cnjuge" : "Informe o CPF do Cônjuge",
		"label.informe.o.email" : "Informe o email",
		"label.informe.o.email.cadastrado" : "Informe o email cadastrado",
		"label.informe.o.endereo.comercial" : "Informe o Endereço Comercial",
		"label.informe.o.logradouro" : "Informe o logradouro",
		"label.informe.o.nmero" : "Informe o número",
		"label.informe.o.nmero.tin" : "Informe o número TIN",
		"label.informe.o.nome" : "Informe o nome",
		"label.informe.o.nome.completo" : "Informe o nome completo",
		"label.informe.o.nome.da.cidade" : "Informe o nome da Cidade",
		"label.informe.o.nome.da.fonte.pagadora" : "Informe o Nome da fonte pagadora",
		"label.informe.o.nome.do.contato" : "Informe o nome do contato",
		"label.informe.o.nome.do.pai" : "Informe o nome do pai",
		"label.informe.o.telefone" : "Informe o telefone",
		"label.informe.o.valor.da.renda.bruta" : "Informe o valor da renda bruta",
		"label.informe.o.valor.da.renda.lquida" : "Informe o valor da renda líquida",
		"label.informe.o.valor.do.imposto.retido.na.fonte" : "Informe o valor do imposto retido na fonte",
		"label.informe.o.valor.em.real" : "Informe o valor em real",
		"label.informe.o.valor.em.real.do.limite.contratado" : "Informe o valor em real do limite contratado",
		"label.limite.contratado" : "Limite Contratado",
		"label.limite.de:.r$1.000,00" : "Limite de: R$1.000,00",
		"label.limite.disponvel:.r$5.000,00" : "Limite Disponível: R$5.000,00",
		"label.limite.disponvel:.r$8.000,00" : "Limite Disponível: R$8.000,00",
		'label.cep.mask': '99999-999',
		"label.link" : "Link",
		"label.listagem" : "Listagem",
		"label.localizar.cliente" : "LOCALIZAR CLIENTE",
		"label.login" : "LOGIN",
		"label.logradouro" : "Logradouro",
		"label.maria.zilda.pagotti./.cpf:.000.399.368-05" : "MARIA ZILDA PAGOTTI / CPF: 000.399.368-05",
		"label.meios.de.comunicao" : "Meios de Comunicação",
		"label.menor.emancipado" : "Menor Emancipado",
		"label.modalidade" : "Modalidade",
		"label.modalidade.da.cesta" : "Modalidade da Cesta",
		"label.nacionalidade" : "Nacionalidade",
		"label.naturalidade" : "Naturalidade",
		"label.nmero" : "Número",
		"label.nmero.da.conta:.00095231-0" : "Número da Conta: 00095231-0",
		"label.nmero.da.conta.99999-9" : "Número da conta 99999-9",
		"label.nmero.tin" : "Número TIN",
		"label.nome" : "Nome",
		"label.nome:.maria.zilda.pagotti" : "Nome: MARIA ZILDA PAGOTTI",
		"label.nome:.maria.zilda.pagotti./.cpf:.000.399.368-05" : "Nome: MARIA ZILDA PAGOTTI / CPF: 000.399.368-05",
		"label.nome.do.cnjuge" : "Nome do Cônjuge",
		"label.nome.da.fonte.pagadora" : "Nome da fonte pagadora",
		"label.nome.da.me:.maria.josé.de.oliveira" : "Nome da mãe: MARIA JOSÉ DE OLIVEIRA",
		"label.nome.da.me:.nilza.cesar" : "Nome da Mãe: NILZA CESAR",
		"label.nome.do.cliente:.vagner.de.paulo" : "Nome do Cliente: Vagner de Paulo",
		"label.nome.do.pai" : "Nome do Pai",
		"label.novo.usurio" : "Novo usuário",
		"label.ocultar.documento" : "Ocultar Documento",
		"label.ocupao" : "Ocupação",
		"label.operao:.001.-.conta.corrente.pf" : "Operação: 001 - Conta Corrente PF",
		"label.operao.comercial" : "Operação Comercial",
		"label.opes" : "Opções",
		"label.pacote.desconto.cesta.de.servios" : "Pacote Desconto Cesta de Serviços",
		"label.padaria.dois.garotos.-.agente.administrativo.-.r$18.000,00" : "Padaria Dois Garotos - Agente Administrativo - R$18.000,00",
		"label.parabns,.voc.j.pode.contratar.o.produto!" : "Parabéns, você já pode contratar o produto!",
		"label.parmetros.da.conta" : "Parâmetros da Conta",
		"label.perfil" : "PERFIL",
		"label.perfil.do.usurio" : "Perfil do Usuário",
		"label.pesquisa.cadastral" : "Pesquisa Cadastral",
		"label.pesquisas.cadastrais" : "PESQUISAS CADASTRAIS",
		"label.por.favor,.digitalize.os.seguintes.documentos:" : "Por favor, digitalize os seguintes documentos:",
		"label.por.favor.informe.seu.login" : "Por favor informe seu login",
		"label.portflio.de.acessos" : "PORTFÓLIO DE ACESSOS",
		"label.possui" : "Possui",
		"label.prestao.mxima.admitida" : "Prestação Máxima Admitida",
		"label.primo/siogp" : "PRIMO/SIOGP",
		"label.principal" : "Principal",
		"label.procurador(es)" : "Procurador(es)",
		"label.produtos.ativos" : "Produtos Ativos",
		"label.produtos.do.cliente" : "PRODUTOS DO CLIENTE",
		"label.profisso:.bancário.e.economiário" : "Profissão: BANCÁRIO E ECONOMIÁRIO",
		"label.profisso/.cdigo.da.ocupao" : "Profissão",
		"label.programa.pontos.caixa?" : "Programa Pontos Caixa?",
		"label.prototipado.no.primo,.suportado.pelo.siogp" : "prototipado no PRIMO, suportado pelo SIOGP",
		"label.pv.responsvel:.0002" : "PV Responsável: 0002",
		"label.quadro.de.valores" : "Quadro de Valores",
		"label.quebra.de.linha.(br)" : "Quebra de linha (br)",
		"label.quero.me.cadastrar" : "QUERO ME CADASTRAR",
		"label.receber.emails" : "Receber Email's",
		"label.receber.notificaes" : "Receber Notificações",
		"label.redigitao.senha" : "Redigitação senha",
		"label.renda.bruta" : "Renda bruta",
		"label.renda.comprovada" : "Renda Comprovada",
		"label.renda.lquida" : "Renda Líquida",
		"label.renda.no.comprovada/informal" : "Renda não comprovada/informal",
		"label.renda.total:.r$1.000,00" : "Renda Total: R$1.000,00",
		"label.responsabilizo-me.pela.exatido.das.informaes.prestadas,..vista.dos.originais.do.documento.de.identidade,.do.cpf.e.outros.comprobatrios.dos.demais.elementos.de.informao.apresentados,.sob.pena.de.aplicao.do.disposto.no.artigo.64,.da.lei.nº.8.383,.de.30/12/1991." : "Responsabilizo-me pela exatidão das informações prestadas, à vista dos originais do documento de identidade, do CPF e outros comprobatórios dos demais elementos de informação apresentados, sob pena de aplicação do disposto no Artigo 64, da Lei nº 8.383, de 30/12/1991.",
		"label.resultado.da.abertura.da.conta.e.contratao.de.servios" : "Resultado da abertura da conta e contratação de serviços",
		"label.resultado.da.digitalizao.de.documentos" : "Resultado da Digitalização do Documento",
		"label.resumo.do.cliente" : "RESUMO DO CLIENTE",
		"label.retornar" : "retornar",
		"label.rg" : "RG",
		"label.roteiro.negocial" : "ROTEIRO NEGOCIAL",
		"label.saques,.transferncias,.pagamentos,.agendamentos.a.partir.de" : "Saques, transferências, pagamentos, agendamentos a partir de",
		"label.selecione.a.data.de.admisso" : "Selecione a data de admissão",
		"label.selecione.a.data.de.nascimento.do.cnjuge" : "Selecione a data de nascimento do Cônjuge",
		"label.selecione.a.opo" : "Selecione a opção",
		"label.selecione.as.opes" : "Selecione as opções",
		"label.selecione.o.item" : "Selecione o item",
		"label.selecione.o.dispositivo" : "Selecione o dispositivo",
		"label.selecione.o.tipo.de.carto" : "Selecione o tipo de cartão",
		"label.sem.rendas.no.comprovadas/informais" : "Sem rendas não comprovadas/informais",
		"label.senha" : "Senha",
		"label.senha.da.conta.gerada.com.sucesso" : "Senha da Conta gerada com sucesso",
		"label.separador.(hr)" : "Separador (hr)",
		"label.servio.de.mensagens.via.celular" : "Serviço de mensagens via celular",
		"label.servios.do.carto" : "Serviços do Cartão",
		"label.sexo" : "Sexo",
		"label.sicow:.problema.na.consulta" : "SICOW: problema na consulta",
		"label.sinad:.problema.na.consulta" : "SINAD: problema na consulta",
		"label.situao:.regular" : "Situação: REGULAR",
		"label.situao.das.notificaes" : "Situação das Notificações",
		"label.sobre" : "SOBRE",
		"label.solicitar.avaliao" : "Solicitar Avaliação",
		"label.solidria" : "Solidária",
		"label.splash" : "SPLASH",
		"label.sub-ttulo" : "Sub-título",
		"label.tabela.filtro.por.colunas" : "Tabela Filtro por Colunas",
		"label.tela.de.cadastramento" : "Tela de Cadastramento",
		"label.tela.de.login" : "Tela de Login",
		"label.tela.de.perfil.do.usurio" : "Tela de Perfil do Usuário",
		"label.tela.de.recuperao.de.senha" : "Tela de recuperação de senha",
		"label.tela.de.splash" : "Tela de Splash",
		"label.tela.principal" : "Tela Principal",
		"label.telefone./.comum.-.residencial.atual.-.(11).97644-8667" : "Telefone / Comum - Residencial Atual - (11) 97644-8667",
		"label.telefone.fixo:.(021).9999-9999.-.data.de.referncia.dd/mm/aaaa.[excluir]" : "Telefone Fixo: (021) 9999-9999 - Data de Referência DD/MM/AAAA [Excluir]",
		"label.termo.de.declarao" : "Termo de Declaração",
		"label.texto" : "Texto",
		"label.timer" : "Timer",
		"label.tipo.de.carto" : "Tipo de Cartão",
		"label.tipo.de.conta" : "Tipo de Conta",
		"label.tipo.de.conta.0001-.conta.corrente" : "Tipo de conta 0001- Conta Corrente",
		"label.tipo.de.fonte.pagadora" : "Tipo de fonte pagadora",
		"label.tipo.de.logradouro" : "Tipo de Logradouro",
		"label.titular:.vagner.de.paulo" : "Titular: Vagner de Paulo",
		"label.titular.(es)" : "Titular (es)",
		"label.titular(es)" : "Titular(es)",
		"label.trocar.a.senha" : "Trocar a Senha",
		"label.ttulo" : "Título",
		"label.tutor(es)" : "Tutor(es)",
		"label.uf" : "UF",
		"label.v1.0" : "v1.0",
		"label.valor.do.imposto.retido.na.fonte" : "Valor do imposto retido na fonte",
		"label.variante" : "Variante",
		"label.voltar" : "Voltar",
		'label.processando' : 'Processando...',
		"label.erro.client.notFound" : " não localizado.",
		"label.agencia" : "Agência",
		"label.profissao" : "Profissão",
		"label.correioeletronico" : "Correio Eletrônico (email)",
		"label.telefonecomum" : "Telefone / Comum - Residência Atual",
		"label.cpf.invalid" : "CPF Inválido",
		"label.nome.mae" : "Nome da Mãe",
		"label.dispositivo" : "Dispositivo",
		"label.codigoProduto" : "Código Produto",
		"label.situacao" : "Situação",
		"label.ocorrencia" : "Ocorrência",
		"label.orientacoes" : "Orientações",
		"label.naoinformado" : "Não informado",
		"label.no" : "Não",
		"label.provide.card" : "Após assinatura do cliente, forneça abaixo o cartão-assinatura digitalizado",
		"label.celular" : "Celular",
		"label.email" : "Email",
		"label.telefoneFixo" : "Telefone Fixo",
		"label.termo" : "         Declaro a veracidade das informações prestadas, sob pena de crime de falsidade ideológica do art. 299 do Código Penal e/ou crime contra o Sistema Financeiro Nacional previsto no art. 19 da Lei nº 7.492, de 16 de Junho de 1986.",
		"label.brasiliaDF" : "Brasília/DF",
		"label.tokenGenerate" : "Token de autorização do Gerente: ",
		"label.autorizacao.number" : "Autorização nº:",
		"label.autorizacao.backend" : "Chamando serviço de autorização. Aguarde",
		"label.autorizacao.denied" : "Autorização não concedida. Realize o fluxo de autorização documental.",
		"label.contratoRelacionamento" : "Contrato de Relacionamento",
		"label.termoAdesaoCesta" : "Termo de Adesão a Cesta",
		"label.regulamentoCesta" : "Regulamento da Cesta",
		"label.dicasSeguranca" : "Dicas de Segurança",
		"label.dataDeDebitoInvalida" : "Valor inválido. Permitido de 1 a 30",
		"label.valorMaiorQueDisponivel" : "Valor é maior que o limite disponível",
		"label.chequeEspecialNegado" : "Contratação de Cheque Especial não pôde ser efetuada.",
		"label.servicoCelularOK" : "Serviços de Mensagem via Celular implantado com sucesso",
		"label.assinaturaEletronicaOK" : "Cadastro de Assinatura Eletrônica realizado com sucesso",
		"label.numeroContaFixoTelaFinal" : "Número da conta 99999-9",
		'label.clique.aqui.para.cancelar.atendimento': 'Clique aqui para cancelar o atendimento',
		"label.data.invalid" : "Data Inválida",
		'label.cancelar.atendimento': 'Cancelar atendimento',
		"label.campo.obrigatorio" : "Campo obrigatório",
		'label.teste.digital.doc': 'Data de Emissão',
		'titulo.cancelar.atendimento' : 'Cancelar Atendimento',
		'titulo.responda.perguntas.aleatorias' : 'Por Favor, responda as perguntas abaixo:',
		'label.deseja.cancelar.atendimento' : 'Deseja cancelar o atendimento?',
		'label.tipo' : 'Tipo',
		'label.naturalidade.uf' : 'Naturalidade UF',
		'label.naturalidade.municipio' : 'Naturalidade Município',
		'titulo.incluir.funcao' : 'Incluir Função',
		'titulo.excluir.funcao' : 'Excluir Função',
		'tooltip.dados.declarados.logradouro' : 'Exemplo: Rio Branco nº 174, 7º andar, Centro',
		'tooltip.dados.declarados.cep' : 'Buscar Cep',
		'tooltip.dados.declarados.tipo.logradouro' : 'Exemplos: Rua, Av, QD etc. Máximo de 3 posições',
		'tooltip.dados.declarados.uf' : 'Formato da SIGLA é XX',
		'tooltip.dados.declarados.valor.total.patrimonio' : 'Informar valor total declarado pelo cliente',
		'tooltip.dados.declarados.senha.eletronica' : 'Senha gerada pelo próprio cliente no cartão assinatura',
		"label.selecione" : 'Selecione'
		
	});

	$translateProvider.preferredLanguage('pt');
	$translateProvider.useSanitizeValueStrategy(null);
}]);