export enum AdministracaoDossieSituacao {
    AGUARDANDO_ALIMENTACAO = '{"key": "AGUARDANDO_ALIMENTACAO", "name": "Aguardando Alimentação", "code": 1, "api": 12}',
    AGUARDANDO_COMPLEMENTACAO = '{"key": "AGUARDANDO_COMPLEMENTACAO", "name": "Aguardando Complementação", "code": 2, "api": 17}',
    AGUARDANDO_TRATAMENTO = '{"key": "AGUARDANDO_TRATAMENTO", "name": "Aguardando Tratamento", "code": 3, "api": 3}',
    ALIMENTACAO_FINALIZADA = '{"key": "ALIMENTACAO_FINALIZADA", "name": "Alimentação Finalizada", "code": 4, "api": 15}',
    ANALISE_SEGURANCA = '{"key": "ANALISE_SEGURANCA", "name": "Análise Segurança", "code": 5, "api": 6}',
    CANCELADO = '{"key": "CANCELADO", "name": "Cancelado", "code": 6, "api": 11}',
    CONFORME = '{"key": "CONFORME", "name": "Conforme", "code": 7, "api": 5}',
    EM_ALIMENTACAO = '{"key": "EM_ALIMENTACAO", "name": "Em Alimentação", "code": 8, "api": 13}',
    EM_COMPLEMENTACAO = '{"key": "EM_COMPLEMENTACAO", "name": "Em Complementação", "code": 9, "api": 18}',
    EM_TRATAMENTO = '{"key": "EM_TRATAMENTO", "name": "Em Tratamento", "code": 10, "api": 4}',
    FINALIZADO = '{"key": "FINALIZADO", "name": "Finalizado", "code": 11, "api": 16}',
    FINALIZADO_CONFORME = '{"key": "FINALIZADO_CONFORME", "name": "Finalizado Conforme", "code": 12, "api": 9}',
    FINALIZADO_INCONFORME = '{"key": "FINALIZADO_INCONFORME", "name": "Finalizado Inconforme", "code": 13, "api": 10}',
    PENDENTE_INFORMACAO = '{"key": "PENDENTE_INFORMACAO", "name": "Pendente Informação", "code": 14, "api": 14}',
    PENDENTE_SEGURANCA = '{"key": "PENDENTE_SEGURANCA", "name": "Pendente Segurança", "code": 15, "api": 7}',
    SEGURANCA_FINALIZADO = '{"key": "SEGURANCA_FINALIZADO", "name": "Segurança Finalizado", "code": 16, "api": 8}',
}
