export const CHECKLIST = {
    CHECKLIST: "cadastro/checklist",
    CHECKLIST_SIM: "SIM",
    CHECKLIST_NAO: "NÃO",
    CHECKLIST_TRUE: "True",
    CHECKLIST_FALSE: "False",
    CHECKLIST_NOT_FOUND: "not-found",
    CHECKLIST_NOVO: "cadastro/checklist/novo",
    CHECKLIST_PESQUISA: "cadastro/checklist",
    CHECKLIST_CONFIRMACAO_EXCLUSAO: "Confirmação exclusão checklist",
    CHECKLIST_REMOVER: "Você tem certeza que deseja remover este checklist ?",
    CHECKLIST_COPIA: "Cópia checklist",
    CHECKLIST_TITLE_OPERACOES: "Checklist com operações associadas",
    CHECKLIST_OPERACOES: "O checklist {id} possui operações associadas, não sendo possível excluí-lo.",
    CHECKLIST_REMOVER_SEM_VINCULACAO_ASSOCIACAO_OPERACAO: "O checklist {id} não possui operações associadas. Você confirma a exclusão do checklist e das vinculações de processos a ele ?",
    CHECKLIST_REMOVER_SEM_ASSOCIACAO_OPERACAO: "O checklist {id} não possui vinculações ou associações a operações. Você confirma a exclusão do checklist?",
    CHECKLIST_REMOVER_SUCESSO: "Checklist {id} Removido com sucesso",
    CHECKLIST_ADICIONADO_SUCESSO: "Checklist {id} cadastrado com sucesso",
    CHECKLIST_ATUALIZADO_SUCESSO: "Checklist {id} atualizado com sucesso",
    CHECKLIST_INATIVADO_SUCESSO: "Checklist {id} inativado com sucesso",
    CHECKLIST_REMOVIDO_SUCESSO: "Checklist {id} removido com sucesso",
    CHECKLIST_EXISTENTE: "Já existe um checklist com este nome. Gentileza escolher outro nome. Caso seja apenas uma nova versão de um mesmo checklist, utilize o padrão 'NOME DO CHECKLIST - V2'."
}