/* Tabela 009 */
---------------

DROP INDEX IF EXISTS "mtrsm001"."ix_mtrtb009_01";
CREATE UNIQUE INDEX "ix_mtrtb009_01" ON "mtrsm001"."mtrtb009_tipo_documento" USING btree ("no_tipo_documento", "ic_processo_administrativo", "ic_dossie_digital", "ic_apoio_negocio", "ic_validacao_cadastral");

DELETE FROM mtrsm001.mtrtb045_atributo_extracao WHERE nu_tipo_documento IN (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE ic_processo_administrativo = true);
DELETE FROM mtrsm001.mtrtb009_tipo_documento WHERE ic_processo_administrativo = true;

INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'ADITIVO CONTRATUAL', 'A', false, 'ADITIVO_CONTRATUAL', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'ATA', 'A', false, 'ATA', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'ATA DE REGISTO DE PREÇO', 'A', false, 'ATA_REGISTRO_DE_PRECO', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'ATESTE', 'A', false, 'ATESTE', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'COMUNICAÇÃO ELETRÔNICA', 'A', false, 'COMUNICACAO_ELETRONICA', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'COMUNICAÇÃO INTERNA', 'A', false, 'COMUNICACAO_INTERNA', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'CONTRATO', 'A', false, 'CONTRATO', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'DECLARAÇÃO DE EXECUÇÃO CONTRATUAL', 'A', false, 'DEC', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'DIARIO OFICIAL DA UNIÃO', 'A', false, 'DIARIO_OFICIAL_UNIAO', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'DOCUMENTOS DIVERSOS', 'A', false, 'ANEXOS', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'EDITAL', 'A', false, 'EDITAL', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'GARANTIA', 'A', false, 'GARANTIA', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'NOTA FISCAL', 'A', false, 'NOTA_FISCAL', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'NOTA JURIDICA', 'A', false, 'NOTA_JURIDICA', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'NOTA TECNICA', 'A', false, 'NOTA_TECNICA', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'OFICIO', 'A', false, 'OFICIO', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'ORDEM DE FORNECIMENTO', 'A', false, 'ORDEM_DE_FORNECIMENTO', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'PARECER', 'A', false, 'PARECER', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'PLANILHA DE CUSTOS', 'A', false, 'PLANILHA_DE_CUSTOS', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'PROCURACAO', 'A', false, 'PROCURACAO', false, true, false, false, false, false);
INSERT INTO mtrsm001.mtrtb009_tipo_documento(nu_versao, no_tipo_documento, ic_tipo_pessoa, ic_validade_auto_contida, no_classe_ged, ic_reuso, ic_processo_administrativo, ic_dossie_digital, ic_apoio_negocio, ic_validacao_cadastral, ic_validacao_documental) VALUES (1, 'RECURSO', 'A', false, 'RECURSO', false, true, false, false, false, false);

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'ADITIVO_CONTRATUAL'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'ADITIVO_CONTRATUAL'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'ATA'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'ATA'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'ATA_REGISTRO_PRECO'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'ATA_REGISTRO_PRECO'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'ATESTE'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'ATESTE'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'COMUNICACAO_ELETRONICA'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'COMUNICACAO_ELETRONICA'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'COMUNICACAO_INTERNA'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'COMUNICACAO_INTERNA'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'CONTRATO'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'CONTRATO'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'DEC'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'DEC'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'DIARIO_OFICIAL_UNIAO'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'DIARIO_OFICIAL_UNIAO'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'ANEXOS'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'ANEXOS'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'EDITAL'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'EDITAL'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'GARANTIA'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'GARANTIA'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'NOTA_FISCAL'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'NOTA_FISCAL'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'NOTA_JURIDICA'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'NOTA_JURIDICA'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'NOTA_TECNICA'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'NOTA_TECNICA'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'OFICIO'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'OFICIO'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'ORDEM_DE_FORNECIMENTO'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'ORDEM_DE_FORNECIMENTO'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'PARECER'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'PARECER'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'PLANILHA_DE_CUSTOS'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'PLANILHA_DE_CUSTOS'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'PROCURACAO'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'PROCURACAO'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');

INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'RECURSO'), 'Emissor do Documento', true, true, 'EMISSOR', false, 'emissor_documento', 'STRING', true, 'INPUT_TEXT', true, 'STRING');
INSERT INTO mtrsm001.mtrtb045_atributo_extracao(nu_versao, nu_tipo_documento, no_atributo_negocial, ic_ativo, ic_ged, no_atributo_ged, ic_calculo_data, no_atributo_documento, ic_tipo_ged, ic_obrigatorio_ged, ic_tipo_campo, ic_obrigatorio, ic_tipo_geral) VALUES (1, (SELECT nu_tipo_documento FROM mtrsm001.mtrtb009_tipo_documento WHERE no_classe_ged = 'RECURSO'), 'Data de Emissão', true, true, 'DATA_EMISSAO', false, 'data_emissao', 'DATE', true, 'INPUT_TEXT', true, 'DATE');
